# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TapErrorReportingV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapErrorReportingV2
	pod 'TapAdditionsKitV2'
	pod 'TapAlertViewControllerV2'
	pod 'TapApplicationV2'
	pod 'TapBundleLocalizationV2'
	pod 'TapNetworkManagerV2'
end
